apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: regapp

spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: regapp
  type: LoadBalancer
    