apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: ng-app

spec:
  containers:
    - name: demo-nginx
      image: nginx
      ports:
      - name: demp-port
        containerPort: 80
    