---
- hosts: eks
# become: true
  user: root

  tasks:
  - name: Deploy the services on kubernetes
    command: kubectl apply -f deployment-service.yml
    
  - name: Updat deployment with new pods if image updated in docker hub 
    command: kubectl rollout restart deployment.apps/dhanush-regapp
